[api_aemet]
API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3JnZXJpdmVyb2RlbG9zcmlvc0BnbWFpbC5jb20iLCJqdGkiOiJiMjlhZmM2Zi0yMTkwLTQ4ZTEtYjlmYy01NGY5OTk3OTc1YjUiLCJpc3MiOiJBRU1FVCIsImlhdCI6MTc0ODk2ODY4NSwidXNlcklkIjoiYjI5YWZjNmYtMjE5MC00OGUxLWI5ZmMtNTRmOTk5Nzk3NWI1Iiwicm9sZSI6IiJ9.90idEjGLaI61xKuPe8sdQtBJ2fdf4gwZmsww11V1VpE"

[supabase]
user = "postgres.njadxjsughjeegmqphqw"
password = "bMxAL3GyGB80D4YK"
host = "aws-0-eu-west-3.pooler.supabase.com"
port = 5432
name="postgres"

[database]
user = "root"
password = "s41nt"
name = "aemet"
host = "localhost"
port = 3306